# Generated by Django 5.0.1 on 2024-02-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100, verbose_name='заголовок новости')),
                ('is_public', models.BooleanField(default=False, verbose_name='для открытой печати')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'news',
                'ordering': ['-updated_at'],
            },
        ),
    ]
