# Generated by Django 5.0.1 on 2024-02-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='full_text',
            field=models.TextField(default=1, verbose_name='полный текст новости'),
        ),
    ]
